library(shiny)
library(here)
library(dplyr)
library(tidyr)
library(plotly)
library(glue)
library(plotly)
library(ggtranscript)
library(jsonlite)
library(SingleCellExperiment)
library(zellkonverter)
library(reticulate)

use_condaenv("/scratch/s/shreejoy/nxu/CIHR/envs")
anndata <- import("anndata")
setwd("/gpfs/fs0/scratch/s/shreejoy/nxu/CIHR/")

count <- anndata$read_h5ad("proc/interactive_heatmap.h5ad")
count_sce <- zellkonverter::AnnData2SCE(count)
saveRDS(count_sce, "patch_spl_app/data/count_sce.rds")
saveRDS(count_sce, "data/count_sce.rds")

count <- anndata$read_h5ad("proc/interactive_heatmap_subclass.h5ad")
count_sce <- zellkonverter::AnnData2SCE(count)
saveRDS(count_sce, "patch_spl_app/data/count_sce_subclass.rds")
